### ISSUE TITLE
StitchData integration failures

### ISSUE THREAD

**Issue by JFulfordMS** [fishtown-analytics/tap-ringcentral#8]
The following is the output log from Stitch. I've validated all credentials are correct and RingCentral app is configured as per requirements.

2020-03-12 14:18:06,946Z   main - INFO Running tap-ringcentral version 1.0.1 and target-stitch version 3.0.2
2020-03-12 14:18:07,020Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-ringcentral --config /tmp/tap_discover_config.json --discover
2020-03-12 14:18:07,930Z    tap - INFO Starting discovery.
2020-03-12 14:18:07,966Z   main - INFO Tap exited normally.
2020-03-12 14:18:07,966Z   main - INFO Saving list of discovered streams
2020-03-12 14:18:07,982Z   main - INFO Saving structure of stream contacts
2020-03-12 14:18:08,007Z   main - INFO Saving structure of stream call_log
2020-03-12 14:18:08,030Z   main - INFO Saving structure of stream company_call_log
2020-03-12 14:18:08,051Z   main - INFO Saving structure of stream messages
2020-03-12 14:18:08,120Z   main - INFO Starting tap: tap-env/bin/tap-ringcentral --config /tmp/tap_config.json
2020-03-12 14:18:09,082Z    tap - INFO Starting sync.
2020-03-12 14:18:09,083Z    tap - CRITICAL 'NoneType' object has no attribute 'streams'
2020-03-12 14:18:09,083Z    tap - Traceback (most recent call last):
2020-03-12 14:18:09,083Z    tap -   File "tap-env/bin/tap-ringcentral", line 11, in <module>
2020-03-12 14:18:09,083Z    tap -     load_entry_point('tap-ringcentral==1.0.1', 'console_scripts', 'tap-ringcentral')()
2020-03-12 14:18:09,083Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 192, in wrapped
2020-03-12 14:18:09,083Z    tap -     return fnc(*args, **kwargs)
2020-03-12 14:18:09,083Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_ringcentral/__init__.py", line 66, in main
2020-03-12 14:18:09,083Z    tap -     runner.do_sync()
2020-03-12 14:18:09,083Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_ringcentral/__init__.py", line 22, in do_sync
2020-03-12 14:18:09,083Z    tap -     streams = self.get_streams_to_replicate()
2020-03-12 14:18:09,084Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_framework/__init__.py", line 26, in get_streams_to_replicate
2020-03-12 14:18:09,084Z    tap -     for stream_catalog in self.catalog.streams:
2020-03-12 14:18:09,084Z    tap - AttributeError: 'NoneType' object has no attribute 'streams'
2020-03-12 14:18:09,111Z   main - INFO Connection check failed
2020-03-12 14:18:09,112Z   main - INFO No tunnel subprocess to tear down
2020-03-12 14:18:09,112Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "'NoneType' object has no attribute 'streams'".

**Comment by SpainTrain** [comment]
We are seeing an identical issue.

CC @bmcniel

**Comment by JFulfordMS** [comment]
Is there anyone actually working issues on this project or should I look elsewhere for a data integration tool?

**Comment by drewbanin** [comment]
hey @JFulfordMS - we don't actively maintain this tap anymore. I think you'll want to consult the Singer fork found here: https://github.com/singer-io/tap-ringcentral

**Comment by JFulfordMS** [comment]
@drewbanin Ok, I'm not able to post on issue on that project. I'm going to StitchData.com and it is choosing the Tap to use and points to the singer-io fork. The error still persists.

**Comment by drewbanin** [comment]
Ah, I understand. I just pinged the Singer team in the `tap-ringcentral` channel on the Singer Slack. Hopefully someone from their team will be able enable issues in the Singer fork and help you get these problems addressed!

**Comment by Kobold** [comment]
Anyone have any luck? I opened an issue in that fork as well. https://github.com/singer-io/tap-ringcentral/issues/13

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
